apiVersion: v1
kind: Service
metadata:
  labels:
    loadBalancer: load-balancer-service
  name: flask-app
spec:
  ports: 
  - nodePort: 30260
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    loadBalancer: load-balancer-service
  type: LoadBalancer
