apiVersion: v1
kind: Pod
metadata:
  labels:
    loadBalancer: load-balancer-service
  name: nginx
  namespace: default
spec:
  volumes: 
    - name: nginx-vol
      configMap: 
        name: nginx-config 
  containers:
  - image: nginx:alpine
    name: nginx
    volumeMounts:
    - name: nginx-vol
      mountPath: /etc/nginx
  
   