apiVersion: v1
kind: Service
metadata:
  labels:
    clusterIP: cluster-ip-service
  name: nginx-service2
spec:
  ports: 
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    loadBalancer: load-balancer-service
  type: LoadBalancer
     